version: '3'

services:

services:

  cadvisor-armv7l:
    image: jahrik/arm-cadvisor:armv7l
    networks:
      - monitor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.arch == arm32v7

  cadvisor-aarch64:
    image: jahrik/arm-cadvisor:aarch64
    networks:
      - monitor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.arch == aarch64

  cadvisor-amd64:
    image: jahrik/arm-cadvisor:x86_64
    networks:
      - monitor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.arch == x86_64

networks:
  monitor:
    driver: overlay
    external: true
