---
services:
  cadvisor:
    image: jahrik/arm-cadvisor:latest
    networks:
      - monitor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global

networks:
  monitor:
    name: monitor
    driver: overlay
    external: true
