version: '3'

services:

  cadvisor:
    image: jahrik/arm-cadvisor:arm32v7
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
